#!/usr/bin/env bash
# Bash script that automatically configure an Ubuntu machine
# to configure your Nginx server so that /redirect_me is
# redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
service nginx restart
