#!/usr/bin/env bash
# Bash script that configures the Nginx server to
# have a custom 404 page that contains the string
# Ceci n'est pas une page.
apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '45 i \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
