#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02)
apt-get -y update
apt-get -y install nginx
sed -i "30 i \\\n\tadd_header X-Served-By $HOSTNAME;\n" \
    /etc/nginx/sites-available/default
service nginx restart
