#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.6
apt-get update
apt-get -y install haproxy=1.6.\*

echo -e 'ENABLED=1' >> /etc/default/haproxy

echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers
backend web_servers
\tbalance roundrobin
\tserver 2321-web-01 35.237.133.200
\tserver 2321-web-02 54.160.239.103
' >> /etc/haproxy/haproxy.cfg
service haproxy restart
