#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and: see 5.

count=1
while [ $count -le 10 ]
do
if [ $count -eq 4 ]
then
echo bad luck
elif [ $count -eq 8 ]
then
echo good luck
else
echo Holberton School
fi
((count++))
done
